sectors = {
    "Auto": ["Auto Ancilaries", "Auto Manufacturers", "Tyres & Rubber Products"],
    "Metals & Mining": [
        "Iron & Steel",
        "Metal Fabrication",
        "Mining/Minerals",
        "Trading - Metals",
    ],
    "Capital Goods": [
        "Electrical - Power Equipment",
        "Industrial Products & Manufacturing",
        "Aerospace & Defense",
        "EMS",
        "Packaging",
        "Ship building & Allied services",
        "Cables - Electricals",
        "Electrical Miscallaneous",
        "Pumps",
        "Glass",
        "Transformers",
        "Railways",
    ],
    "Healthcare": [
        "Pharmaceuticals",
        "Hospitals",
        "Medical-Diversified",
        "Medical Diagnostics",
        "Healthcare Research Analytics & Technology",
        "Biotechnology",
        "Medical Equipment & Supplies",
    ],
    "Chemicals": [
        "Chemicals Specialty",
        "Agro chemicals",
        "Fertilizers",
        "Chemicals-Plastics",
        "Medical Equipment & Supplies",
        "Chemicals-Basic",
        "Petrochemicals",
    ],
    "Consumer Services": [
        "Hotels",
        "Education Services",
        "E- Commerce",
        "Tour & Travel services",
        "Diversified Retail",
        "Restaurants",
        "Speciality Retail",
        "Retail-Department Stores",
        "Auto Dealer",
        "Amusement Parks/ Other Recreation",
    ],
    "Financial Services": [
        "Finance & Investment",
        "NBFC",
        "Investment Banking & Broking",
        "Financial Services-Specialty",
        "Private Banks",
        "PSU Banks",
        "Housing Finance",
        "Asset Management",
        "Life Insurance",
        "Credit Rating Agencies",
        "Holding Company",
        "General Insurance",
        "Railways",
    ],
    "Construction": [
        "Civil Construction",
        "Cement",
        "Construction Products Miscallaneous",
        "Railways",
    ],
    "FMCG": [
        "Food Products",
        "Tea & Coffee",
        "Breweries & Distilleries",
        "Personal Care",
        "Sugar",
        "Dairy Products",
        "Edible Oils & Solvent Extraction",
        "Agro Products",
        "Tobacco",
        "Stationary",
        "Other Beverages",
    ],
    "Telecommunication": [
        "Telecom - Cellular & Fixed line services",
        "Telecom - Equipment & Accessories",
        "Other Telecom Services",
        "Telecom - Infrastructure",
        "TV Broadcasting & Software",
        "Railways",
    ],
    "IT": [
        "Software Services",
        "Software Products",
        "Computer Hardware",
        "Computer-Networking",
        "Consulting Services",
        "Telecom - Equipment & Accessories",
        "Other Telecom Services",
    ],
    "Power": ["Power Generation & Distribution", "Energy-Alternative"],
    "Services": ["Logistics", "Diversified Commercial Services", "Airlines"],
    "Utilities": ["Water Supply & Management", "Waste Management"],
    "Diversified": ["Diversified Operations"],
    "Textiles": ["Textiles", "Apparels"],
    "Oil Gas & Consumable Fuels": [
        "Oil & Gas-Field Services",
        "Oil & Gas-Refining & Marketing",
        "Oil & Gas Drilling",
        "Lubricants",
        "Gas Distribution",
        "Oil & Gas-Integrated",
        "Coal Products",
        "Oil Exploration & Production",
    ],
    "Media Entertainment & Publication": [
        "Media & Entertainment",
        "Advertising",
        "Print Media",
        "TV Broadcasting & Software",
        "Web Services",
        "Film Production & Distribution",
        "Electronic Media",
    ],
    "Consumer Durables": [
        "Jewellery",
        "Household Appliances",
        "Leisure Products",
        "Paints",
        "Footwear",
        "Home Furnishing",
    ],
    "Realty": ["Real Estate", "Construction Residential & Commercial"],
    "Forest Materials": ["Paper & Paper Products", "Wood Products"],
}
